### ISSUE TITLE
No-Flux approach

### ISSUE THREAD

**Issue by tpluscode** [devinivy/polymer-funky-flux#2]
Hi. Nice work with using behaviors to integrate Reflux and Polymer. I should have thought about that myself ;)

I'd like to hear your opinion on my alternative approach, where I completely ditch any Flux flavour and simply use the document as a dispatcher and send custom events. I also prefer the declarative binding but I guess it's just a matter of preference.

Of course this way I sacrifice out-of-the-box action synchronization. Also I'm not a JS pro :wink:. Are there possible performance drawbacks?

Also I've been thinking how you decouple stores from actual API calls. Is this the Flux way? I though that stores were actually responsible for contacting the back-end, etc and updating the state when necessary...

**Comment by tpluscode** [comment]
Oh, of course! Please do have a look at [my fork](https://github.com/tpluscode/polymer-faux-flux/commit/a49afb61d5c27a118e8aecb26106bdfa80c255bc)

**Comment by devinivy** [comment]
Hey!  Thanks for bringing this stuff up.  I totally looked through your polymer-flux repo a bunch of times while thinking about using Polymer with flux :)

Your branch of this repo looks cool and I'll definitely keep an eye on it!  I know you're not the only person thinking about using Polymer on its own to implement flux.  Some folks in the Polymer slack were chatting about it recently.  And then there's [this](http://codepen.io/mikkokam/full/YXLgad) codepen.  It's all very interesting stuff to me.

> I'd like to hear your opinion on my alternative approach, where I completely ditch any Flux flavour and simply use the document as a dispatcher and send custom events.

I think that using the document as a dispatcher is sound as far as the pattern goes– it should work fine for implementing some form of flux.  There are two reasons that I prefer events that live outside the DOM.
1. The DOM is slow.  The action-event would have to travel up and down the DOM tree per the bubble/capture cycle.  Reflux actions are dispatched quickly because they basically just call each of a list functions (the subscribers) in an array.  It's mechanically simpler and quicker.
2. That would unnecessarily intermingle your actions and your view layer.  And it would be tempting to think of the path that the action-event travels (as it bubbles through the DOM) as being meaningful or useful, but in reality I think that it's a distraction.  I like keeping the actions and stores as separate from the view as possible.  If they are completely separated, then the view layer could be replaced entirely by something else with minimal hassle.  Using funk, this is violated somewhat, because the stores are Polymer elements.  There's a good reason for that, though– we want the views to subscribe to the stores using "native" Polymer data-binding.

> I also prefer the declarative binding but I guess it's just a matter of preference.

Are you referring to how the stores subscribe to the actions?  Or how the views subscribe to the stores?  In either case, you're probably right!  I would especially like to make the stores subscribing to the actions declarative in this repo.

> Also I've been thinking how you decouple stores from actual API calls.

I think the jury is still out on this.  Some people do put that kind of stuff in their stores.  It can be okay.  The key (as far as I'm concerned) is that the stores' subscribing methods must make any changes to the store _synchronously_.  The way this is handled in reflux is that certain actions have "completed" and "failed" sub-actions.  While each one of those actions and sub-actions are responded to by the stores immediately, of course there may be a gap in time between firing the main action (e.g. `getProducts()`) and the sub-action that denotes its successful completion (e.g. `getProducts.completed(products)`).

What are your thoughts on all of this?

**Comment by devinivy** [comment]
Also– these are two must-see repos for using Polymer with flux, if you haven't seen them yet:
https://github.com/balloob/home-assistant-polymer
https://github.com/balloob/home-assistant-js

**Comment by devinivy** [comment]
Closing this, simply due to age– happy to reopen if there are more thoughts to throw around.
